name: sda
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - h5py=3.7.0
  - jupyter=1.0.0
  - numpy=1.23.5
  - pip=22.3.1
  - pyfftw=0.12.0
  - pyqg=0.7.2
  - python=3.9.16
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - xarray=2023.8.0
  - pip:
    - dawgz==0.4.1
    - einops==0.6.1
    - jax==0.4.4
    - jaxlib==0.4.4
    - matplotlib==3.6.2
    - POT==0.9.0
    - seaborn==0.12.2
    - tqdm==4.64.1
    - wandb==0.13.10
    - zuko==0.1.4
